# --- Users ---
USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

# --- Recipes ---
RECIPE_NAME_MAX_LENGTH = 200
MIN_COOKING_TIME_VALUE = 1
MIN_AMOUNT_VALUE = 1

# --- Ingredients ---
INGREDIENT_NAME_MAX_LENGTH = 200
INGREDIENT_UNIT_MAX_LENGTH = 50

# Лимит списка рецептов в подписках
RECIPES_LIMIT_IN_SUBSCRIPTION_DEFAULT = 3

# Pagination
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100
